# pod-with-config1.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nni-test
spec:
  containers:
    - name: nni-test-container
      image: czh1998/nnidemo
      command: []
      env:
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: my-config-1
              key: my.how
  restartPolicy: Never