apiVersion: v1
kind: Service
metadata:
  name: nni-manager-svc
  namespace: nni-resource
  labels:
    app: nni-manager-svc
spec:
  type: NodePort
  ports:
    - port: 8000
  selector:
    app: nni-manager-pod